# TMDB movies

Load all the necessary packages

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.dates as md

Load the dataset into a DataFrame and inspect the first rows of the DataFrame.

In [4]:
df = pd.read_csv('TMDB-movies-small.csv')
df.head()

,Unnamed: 0,id,title,vote_average,vote_count,status,release_date,revenue,runtime,budget,...,genres,production_companies,production_countries,spoken_languages,cast,director,director_of_photography,writers,producers,music_composer
0,11,16,Dancer in the Dark,7.868,1697,Released,2000-09-01,40061153.0,140,12500000.0,...,"Drama, Crime","Lantia Cinema & Audiovisivi, Fine Line Feature...","Argentina, Denmark, Finland, France, Germany, ...",English,"Bobo Eriksson, Caroline Sascha Cogez, Bo Weste...",Lars von Trier,Robby Müller,"Sjón, Lars von Trier","Leo Pescarolo, Peter Aalbæk Jensen, Vibeke Win...",Björk
1,26,55,Amores Perros,7.600,2475,Released,2000-06-16,20908467.0,154,2000000.0,...,"Drama, Thriller","Altavista Films, Zeta Film",Mexico,Español,"Gerardo Campbell, Rosa María Bianchi, Ricardo ...",Alejandro González Iñárritu,Rodrigo Prieto,Guillermo Arriaga,"Martha Sosa Elizondo, Francisco González Compe...",Gustavo Santaolalla
2,31,64,Talk to Her,7.579,1233,Released,2002-03-15,64803131.0,112,0.0,...,"Drama, Romance","Vía Digital, Good Machine, El Deseo, Atresmedia",Spain,Español,"Carlos García Cambero, Leonor Watling, Pina Ba...",Pedro Almodóvar,Javier Aguirresarobe,Pedro Almodóvar,"Michel Ruben, Agustín Almodóvar","Alberto Iglesias, Vicente Amigo"
3,32,65,8 Mile,7.134,6958,Released,2002-11-08,242875078.0,111,41000000.0,...,"Drama, Music","Mikona Productions, Imagine Entertainment","Germany, United States of America",English,"Malik Barnhardt, Mike Bell, Allen Adams, Abdul...",Curtis Hanson,Rodrigo Prieto,Scott Silver,"Jimmy Iovine, Jim Whitaker, Brian Grazer, Greg...",NaN
4,38,71,Billy Elliot,7.600,3691,Released,2000-09-28,109280263.0,110,5000000.0,...,"Drama, Comedy, Music","StudioCanal, BBC Film, Tiger Aspect, Arts Coun...","France, United Kingdom, United States of America",English,"Lee Williams, Colin MacLachlan, Neil North, Pa...",Stephen Daldry,Brian Tufano,Lee Hall,"Jonathan Finn, Natascha Wharton, Tessa Ross, D...",Stephen Warbeck

Create a new DataFrame with all the movies released in 2000. Tip: Format the release dates as pandas datetime objects. Inspect the amount of rows in the new DataFrame.

In [9]:
ndf = df[df["release_date"].contains(2000)]
ndf

AttributeError: 'Series' object has no attribute 'contains'

Create a new DataFrame df_topmovies which only incorporates the rows with the movies of the year 2000 who get an average score of at least 9. Compare the total rows of the original dataframe with df_topmovies. (Tip: use shape)

Replace all NaN's with 0.

Plot the data using a graph with on the x-axis the release dates and on the y-axis the runtime of the film.
* Use appropriate labels and titles
* Change the ticks and tick labels so every month has a tick and as label the abbreviation of the month (Jan, Feb, March etc.)
* Change the color of the graph
* Show a grid
* Show the legend